version: '3.9'

services:
  php:
    image: php_for_bulletin_board
    working_dir: /home/app/public  # ドキュメントルートを public フォルダに変更
    build:
      context: ./
      dockerfile: Dockerfile.my_php_apache
    tty: true
    stdin_open: true
    stop_signal: SIGKILL
    restart: unless-stopped
    environment:
      DB_HOST: 'db'
      DB_PORT: '3306'
      DB_NAME: 'Chime_board'
      DB_USER: 'root'
      DB_PASS: 'password123456'
    ports:
      - ${PORT:-8080}:80
    volumes:
      - ./public:/home/app/public  # 相対パスでホストの public フォルダをコンテナの public フォルダにマウント

  db:
    image: mysql:8.0
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password123456
      MYSQL_DATABASE: Chime_board
      MYSQL_USER: root
      MYSQL_PASSWORD: password123456
    ports:
      - 3306
    volumes:
      - db-data:/var/lib/mysql

  myadmin:
    image: phpmyadmin/phpmyadmin:5.1.1
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: password123456
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - ${DB_ADMIN_PORT:-8081}:80

volumes:
  db-data:
